### ISSUE TITLE
Possibilité de créer des sous-catégories

### ISSUE THREAD

**Issue by alain01** [GregMage/xmarticle#10]
Bonjour,
des sous catégories seraient intéressantes

Exemple 1 : 
Définir la catégorie "Liens" et des sous-catégories outils, modules, thèmes...

Exemple 2 :
Définir la catégorie "Fiche cuisine" et des sous-catégories "Entrées", "Plats" et "Desserts"

**Comment by Heyula** [comment]
A really great module thanks a lot.
adding images for additional areas would be great.
I am making a theme of your modules. I hope you like it.
**xmnews**
https://demo.erenyumak.com/modules/xmnews/index.php
**xmcontent**
https://demo.erenyumak.com/modules/xmcontent/
**xmcontact**
https://demo.erenyumak.com/modules/xmcontact/

**Comment by alain01** [comment]
Hi,
not in the good place but nice comments ! 
I like so much your condensed blocks news !

**Comment by GregMage** [comment]
Les sous catégories ne sont pas prévues
