### ISSUE TITLE
truncateHtml' is not implemented

### ISSUE THREAD

**Issue by yvescesso** [GregMage/xmarticle#6]
Bonjour Grégory,
Pour le site Xoops d'une association, accessible aux seuls membres, je recherche un module vitrine pour présenter des articles qui seront commandés par email pour faire des commandes groupées au niveau de l'association.
Je crois que xmarticle pourrait convenir, peux-tu me le confirmer?

J'ai installé le module sur Xoops 2.5.10 pour essai
une catégorie et un article créé j'ai cette erreur bloquante quand je veux afficher l'article:
Error : Smarty error: [in db:xmarticle_article.tpl line 18]: [plugin] modifier 'truncateHtml' is not implemented (core.load_plugins.php, line 118)
Peux-tu me dire comment implémenter "truncateHtml"?

**Comment by yvescesso** [comment]
Top désolé je n'avais pas vu la réponse faite à Alain !
en local je suis sous Xoops 2.5.9,  j'ai corrigé çà et ça marche.

**Comment by GregMage** [comment]
Bonjour,

Je pense que ce module peut convenir, par contre il n'est pas encore terminé mais 95% des fonctionnalités sont implantées.
