### ISSUE TITLE
Suppression champs

### ISSUE THREAD

**Issue by alain01** [GregMage/xmarticle#8]
Bonjour,
Quand on supprime un champs, dans la page de gestion des champs, un message demandant confirmation apparaît.
Je pense que cela n'est pas suffisant car en fait cela supprime les valeurs de ce champs pour l'ensemble des fiches qui utilisent ce champs.
Le message pourrait être : 
"Attention, en supprimant ce champs, vous allez supprimer les données de ce champs pour l'ensemble des articles qui l'utilisent."

**Comment by GregMage** [comment]
Bonne remarque! Je vais intégrer cela prochainement
